version: '3.7'

services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "short"
    restart: on-failure
    ports:
      - "5432:5432"
    networks:
      - shortlink-local

networks:
  shortlink-local:
    name: shortlink-local